[project]
name = "qql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "psycopg2-binary>=2.9.10",
    "sqlglot>=27.14.0",
    "rich",
    "plotext",
    "matplotlib>=3.10.6",
]
